### ISSUE TITLE
Clickable ads

### ISSUE THREAD

**Issue by oFilipMalinowski** [kslimani/clappr-ima-plugin#11]
Ads which are available on `https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags` can be clicked, which then redirects to some google website. I am wondering if it is possible to disable redirecting when clicking on ad?

**Comment by kslimani** [comment]
From ad server point of view, if there is no "ClickThrough" or "ClickTracking" in ad server response, i think that IMA SDK display the video ad without clickable elements.

I have made a simple example VAST 2.0 tag url : `https://diffusepro.com/video-ad/vast/linear/vast2_noclickurl.xml`. In this VAST, i removed the `<VideoClicks>` xml element.

Note that some ad server (for example Google Ad Manager) require click url to be filled in order to create creative set.

From a javascript point of view, you could "intercept" mouse click on ad display container.
_(or adding [custom click element](https://github.com/kslimani/clappr-ima-plugin/issues/9#issuecomment-516378575))_

AFAIK, i did not see any option in IMA SDK to disable click through.
_(most common goal of an ad is to make to user click on it)_

**Comment by oFilipMalinowski** [comment]
Thanks for explanation.
From what I read in referenced issue, it is necessary to add optional param `opt_clickTrackingElement`. Is it already there?

**Comment by kslimani** [comment]
It is not implemented yet in ima-ad-player sub-project.

Also, does your ad server handle audio only creative set ?
_(ad server which handle audio only ad may have click through url as optional configuration parameter)_.

**Comment by oFilipMalinowski** [comment]
Cloud team from our department is still finalizing the specification of ad service. Therefore I'm not yet able to say if it's going to support it or not yet. For sure video creative ads will be there.

**Comment by kslimani** [comment]
I released a new version with latest [ima-ad-player](https://github.com/kslimani/ima-ad-player) with new `clickTracking` configuration option.

**Comment by oFilipMalinowski** [comment]
Thanks. I'll give it some testing and provide you feedback.

**Comment by oFilipMalinowski** [comment]
Works as expected. Can be closed. Thanks!
